# Generated by Django 3.1.5 on 2023-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueType',
            fields=[
                ('due_id', models.AutoField(primary_key=True, serialize=False)),
                ('due_name', models.CharField(max_length=255)),
            ],
        ),
    ]
