# Generated by Django 3.1.5 on 2023-04-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0002_duetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('check1', models.BooleanField()),
                ('check2', models.BooleanField()),
                ('due_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_procedures.duetype')),
            ],
            options={
                'unique_together': {('due_type', 'roll_no')},
            },
        ),
    ]
