# Generated by Django 3.1.5 on 2023-04-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_procedures', '0003_newdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdue',
            name='roll_no',
            field=models.CharField(max_length=50),
        ),
    ]
